services:
  - type: web
    name: dont-sang-plus
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "./build.sh"
    startCommand: "gunicorn dont_sang_plus.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dont-sang-plus-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: ALLOWED_HOSTS
        sync: false

databases:
  - name: dont-sang-plus-db
    databaseName: dont_sang_plus_db
    user: dont_sang_plus_user
    plan: free
